### ISSUE TITLE
Fails to decode .bsor file when using make_bsor()

### ISSUE THREAD

**Issue by codesftdev** [Schippi/py-bsor#8]
The erroring code:
```
with open(r"dataset\538864fbdcf76377b2cca9024149ddb0e851cd44.bsor", "r") as f:
    bsor = make_bsor(f)
```

The error:
```
Traceback (most recent call last):
  File "c:\Users\Code\Documents\Programming\CyberSoft\direction.py", line 373, in <module>
    bsor = make_bsor(f)
           ^^^^^^^^^^^^
  File "C:\Users\Code\AppData\Local\Programs\Python\Python311\Lib\site-packages\bsor\Bsor.py", line 602, in make_bsor
    m.magic_number = decode_int(f)
                     ^^^^^^^^^^^^^
  File "C:\Users\Code\AppData\Local\Programs\Python\Python311\Lib\site-packages\bsor\Decoder.py", line 5, in decode_int
    bytes = fa.read(4)
            ^^^^^^^^^^
  File "C:\Users\Code\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 444: character maps to <undefined>
```
The BSOR file (in the zip, github hates .bsor files)
[erroring.zip](https://github.com/user-attachments/files/17882665/erroring.zip)

**Comment by codesftdev** [comment]
others can't reproduce this so i'm closing this for now
